### ISSUE TITLE
'Anonymisation' des champs user, password, latitude et longitude dans log debug

### ISSUE THREAD

**Issue by Peboli** [kavod/KKPA#1]
Bonsoir,

Dans le log du debug les variables user, password, latitude et longitude apparaissent en clair alors qu'elles devraient être 'anonymisée'

**Comment by kavod** [comment]
Bonjour @Peboli ,

Concernant les coordonnées GPS, j'aurais besoin de connaitre avec précision le format renvoyé par Kasa dans ton cas (avec virgules ? avec point ? entre guillemets ? etc.). Pour info, pour ma v2, j'ai uniquement des chiffres (pas de décimales) et les clefs se terminent pas "_i" (ça ne semble pas être le cas sur ta v1).

De même, pour les user/passwords, le log que tu m'as précédemment envoyé ne semblent pas apparaître. J'aurais besoin de voir plus exactement à quel endroit ils sont.
 
J'aurais donc besoin que tu me renvoies tes logs en anonymisant manuellement ces informations tout en gardant le format (y compris les guillemets éventuels qui entoureraient la données). Exemple :
username : mon.email@a.moi
password : reGardePas
longitude : 1234.5678
latitude : 1234.5678
Avec un peu de chance, tu as une latitude négative, auquel cas je veux bien que tu laisses le signe négatif apparaître (pour savoir s'il est avant ou après le chiffre).

Merci encore pour tes retours

**Comment by Peboli** [comment]
Bonjour @kavod ,

Je te joins un fichier avec trois lignes de log intactes contenant pour la première les infos de login et pour les deux suivantes les infos avec la position, une positive et l'autre négative.
Je ne suis malheureusement pas en latitudes négatives, j'aurais un peu plus chaud ;)
Je suis en Belgique, donc tout est positif niveau latitude et longitude, mais je viens de rentrer manuellement des coordonnées négatives 'bidon' dans mon application Kasa pour simuler ce cas.
J'ai effectivement vu ton regex avec (_i) dans la recherche de clé, je ne comprenais pas vraiment le pourquoi par rapport à ce que je recevais.
Je n'avais pas mis la ligne avec user/password dans le précédent log envoyé, c'était pour moi sans intérêt par rapport au problème initial.

Bonne journée !
[log_kkasa.txt](https://github.com/kavod/KKPA/files/2643327/log_kkasa.txt)

**Comment by kavod** [comment]
Longitude / latitude normalement réglé.
J'ai encore un soucis sur le user / password. Je vous tiens au courant (pas toujours dans les meilleures conditions quand je suis en déplacement ;) )

**Comment by Peboli** [comment]
Bonsoir @kavod,

La latitude c'est bon, mais la longitude n'est pas remplacée, cela me retourne ceci dans le log : \"latitude\":0,\"longitude\":5.500000 (j'ai 5.5 de forcé via mon appli Kasa)
Pas de panique @kavod , il n'y a absolument aucune urgence, ce n'est pas un problème qui empêche le plugin de fonctionner !
